services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    shm_size: 2g
    ports:
      - "4444:4444"
  mocha:
    build: .
    container_name: mocha-tests
    user: ${USER_ID}
    network_mode: host
    volumes:
     - ./test/output:./test/output
